### ISSUE TITLE
IBM Cloud Kubernetes Update 1.11 is not using docker anymore

### ISSUE THREAD

**Issue by gluehbirnenkopf** [ibm-cloud-architecture/refarch-cloudnative-devops-kubernetes#16]
Hello all,

As IBM is switching IBM Cloud Kubernetes from Dockerd to Containerd.
(https://console.bluemix.net/docs/containers/cs_versions.html#containerd)

the pipeline does not work anymore:
https://issues.jenkins-ci.org/browse/JENKINS-53297

**Comment by fabiogomezdiaz** [comment]
I updated the pipelines to use a Docker-in-Docker image to avoid relying on the host's Docker Daemon. This is also best practice as there won't be any orphaned containers (not managed by Kubernetes) left behind in case of errors.

https://github.com/ibm-cloud-architecture/refarch-cloudnative-bluecompute-web/blob/spring/Jenkinsfile#L32

Please reopen this issue if you see the same issue come up again. Else, please open a new issue.

Thanks
