### ISSUE TITLE
Blocked at step 2

### ISSUE THREAD

**Issue by kKronstainBrown** [ibm-cloud-architecture/refarch-cloudnative-devops-kubernetes#5]
I got stuck on step 2:

```
kristins-mbp:jenkins kakronst@us.ibm.com$ helm install --name jenkins --set Master.ImageTag=2.67 stable/jenkins
Error: error validating "": error validating data: found invalid field initContainers for v1.PodSpec
```

I see that initContainers section in here:
https://github.com/kubernetes/charts/blob/master/stable/jenkins/templates/jenkins-master-deployment.yaml

But I'm not sure what needs done to get around the issue. Any help you can provide?

**Comment by fabiogomezdiaz** [comment]
@kKronstainBrown I have since updated the Jenkins chart installation with the latest version at the time of writing. Please give it a shot and re-open the issue if you have the same issue. Else, open a new one.
