### ISSUE TITLE
template error

### ISSUE THREAD

**Issue by ghost** [ibm-cloud-architecture/refarch-cloudnative-devops-kubernetes#8]
There is a error when trying to export SERVICE_IP:

$ export SERVICE_IP=$(kubectl get svc --namespace default jenkins --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}")

error: error executing template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}": template: output:1:10: executing "output" at <index .status.loadBa...>: error calling index: index of untyped nil

**Comment by fabiogomezdiaz** [comment]
I updated the README with new instructions, give those a try and reopen the issue if you still have the same issue. Else, open a new one
